---
- name: Mise en œuvre d'un service Nginx
  hosts: www
  gather_facts: false
  become: true

  tasks:
    - name: Installation du paquet Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Configuration du service systemd
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true

    - name: Copy du fichier index.html
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html

    - name: Modification du port d'écoute IPV4
      ansible.builtin.lineinfile:
        dest: /etc/nginx/sites-enabled/default
        regex: listen 80[ ]
        line: "\tlisten 8080 default_server;"
      notify:
        - reload_nginx

    - name: Modification du port d'écoute IPV6
      ansible.builtin.lineinfile:
        dest: /etc/nginx/sites-enabled/default
        regex: :80[ ]
        line: "\tlisten [::]:8080 default_server;"
      notify:
        - reload_nginx

  handlers:
    - name: Rechargement de la configuration
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
      listen:
        - reload_nginx
