---
- name: Playbook initial
  hosts: all
  gather_facts: false

  vars:
    var_1: OKAY

  tasks:
    - name: Module ping
      ansible.builtin.ping:
        data: "{{ var_1 }}"
      register: ping_result

    - name: Module debug
      ansible.builtin.debug:
        msg: "Résultat ping: {{ ping_result.ping | lower }}"
