---
- name: Module shell
  hosts: www
  gather_facts: false

  vars:
    USER: "{{ LOGIN | default('root') }}"

  tasks:
    - name: Module shell
      ansible.builtin.shell: grep "^{{ USER }}:" /etc/passwd
      changed_when: false
      register: shell_result
      failed_when: shell_result.rc > 1

    - name: Utilisateur inexistant
      ansible.builtin.debug:
        msg: "Utilisateur {{ USER }} inexistant" 
      when: shell_result.rc == 1
